# trigger:
# - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: PlayingVariables
    jobs:
      - job: PrintVariable
        steps:
        - bash: echo $(Build.id)
        - bash: java -version

  # - stage: Dev
  #   dependsOn: Build
  #   jobs:
  #     - job: DeployDev
  #       steps:
  #       - script: echo Running in Dev Environment
  #         displayName: Dev_Deployment
  
  # - stage: QA
  #   dependsOn: Build
  #   jobs:
  #     - job: DeployQA
  #       steps:
  #       - script: echo Running in QA Environment
  #         displayName: QA_Deployment
    
  # - stage: PROD
  #   dependsOn:
  #   - QA
  #   - Dev
  #   jobs:
  #     - job: DeployProd
  #       steps:
  #       - script: echo Running in PROD environmnet
  #         displayName: PROD_Deployment