trigger: none

pool:
  #vmImage: ubuntu-latest
  name: linux-machine 
stages:
  - stage: A
    jobs:
      - job: JobA
        steps:
          - script: echo "Job A of Stage A " , $hostname
      - job: JobB
        dependsOn: JobA
        steps:
         - script: echo "Job B of Stage A" 

  - stage: B
    dependsOn: A
    jobs:
      - job: Job1
        displayName: Job1StageB
        steps:
        - script: echo "Job 1 of Stage B"

      - job: Job2
        displayName: Job2StageB
        dependsOn: Job1
        steps:
        - script: echo "Job 2 of Stage B"

  - stage: C
    dependsOn: A
    jobs:
      - job: A1
        displayName: JobA1StageC
        steps:
          - script: echo "A1 from Stage C"
        
  - stage: D
    dependsOn:
    - B
    - C
    jobs:
      - job: AD1
        displayName: JobAD1StageD
        steps:
        - script: echo "Job AD1 from Stage D"
