---
- hosts: all
  become: yes

  tasks:
    - name: "Run a shell command and display its result"
      shell: "uname" 
      register: uname_result
    - debug: msg="{{ uname_result.stdout }}"

- hosts: dev
  become: yes

  tasks:
    - name : "Try Ping"
      action: ping
